#!/bin/bash

set -e

jupyter="/opt/conda/bin/jupyter"

if [ -x  "$jupyter" ]
then
    "$jupyter" notebook --notebook-dir=/opt/notebooks --ip=0.0.0.0 --port=8888 --no-browser --allow-root
else
    echo "no jupyter"
fi